# Generated by Django 2.0.4 on 2018-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Parent/Guardian's Name"),
        ),
    ]
